node {

	stage('Checkout') {
		// build on git push trigger
		properties([pipelineTriggers([pollSCM('* * * * *')])])
	
		// checkout code from repository
		checkout scm
	}
	
	switch(env.BRANCH_NAME) {
		case "master":
			// dont change the version
			break
		default:
			stage('Versioning') {
				withMaven(
						maven: 'maven-3.3.9') {
					// run the maven version setting
					// set version to branch name
					// branch name gets SNAPSHOT extension to be deployed in libs-snapshot-local
					sh "mvn versions:set -DnewVersion=${env.BRANCH_NAME}-SNAPSHOT -DgenerateBackupPoms=false"
				}
			}
			break
	}
	
	stage('Deploy') {
		withMaven(
				maven: 'maven-3.3.9') {		
			// run the maven build
			sh "mvn clean deploy"
		}
	}
	
}